name: "Build and push apk"

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.2'
    - run: flutter clean
    - run: flutter pub get
    - name: Bump version
      run: |
        VERSION=$(grep version: pubspec.yaml | awk '{print $2}')
        NEW_VERSION=${{ github.ref_name }}
        sed -i "s/version: $VERSION/version: $NEW_VERSION/" pubspec.yaml
    - name: Build Android APK
      run: flutter build apk --release
    - name: Rename APK
      run: mv $GITHUB_WORKSPACE/build/app/outputs/flutter-apk/app-release.apk $GITHUB_WORKSPACE/build/app/outputs/flutter-apk/demo_v${{ github.ref_name }}.apk
    - name: Push APK to Releases
      uses: actions/upload-artifact@v2
      with:
        name: demo_v${{ github.ref_name }}.apk
        path: |
          ${{ github.workspace }}/build/app/outputs/flutter-apk/demo_v${{ github.ref_name }}.apk

    - name: Upload APKs
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
      with:
        upload_url: 'https://api.github.com/repos/jumaboyevich/demo_ci_cd.git/releases/latest'
        asset_path: ${{ github.workspace }}/build/app/outputs/flutter-apk/demo_v${{ github.ref_name }}.apk
        asset_name: taqsit_v${{ github.ref_name }}.apk
        asset_content_type: application/vnd.android.package-archive