name: "Increment Version and Create release"

on:
  push:
    branches:
      - main

jobs:
  incrementVersion:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.2'
    - run: flutter clean
    - run: flutter pub get
    
    - name: Increment version
      run: |
        current_version=$(grep 'version: ' pubspec.yaml | awk '{print $2}')
        echo "Current version is $current_version"
        # Increment version number
        new_version=$(echo $current_version | awk -F '+' '{print $1}' | awk -F '.' '{printf "%d.%d.%d", $1, $2, $3 + 1}')
        new_build_number=$(echo $current_version | awk -F '+' '{print $2 + 1}')
        new_version_with_build="$new_version+$new_build_number"
        echo "New version is $new_version_with_build"
        # Update pubspec.yaml with new version
        sed -i "s/version: $current_version/version: $new_version_with_build/g" pubspec.yaml

    - name: Commit and push updated version
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@users.noreply.github.com'
        git commit -am "Increment version to to $new_version_with_build"
        git push
     
    # - name: Extract current version
    #   id: extract_version
    #   run: |
    #     VERSION=$(grep -oP 'version: \K[0-9.]+(\+\d+)?' pubspec.yaml)
    #     echo "::set-output name=version::$VERSION"
    # - name: Increment version
    #   id: increment_version
    #   run: |
    #     CURRENT_VERSION=${{ steps.extract_version.outputs.version }}
    #     NEW_VERSION=$(echo "$CURRENT_VERSION" | awk -F '+' '{print $1"+"($NF+1)}')
    #     echo "::set-output name=new_version::$NEW_VERSION"
    # - name: Update version in files
    #   run: |
    #     NEW_VERSION=${{ steps.increment_version.outputs.new_version }}
    #     sed -i "s/version: ${CURRENT_VERSION}/version: ${NEW_VERSION}/" pubspec.yaml

    # - name: Commit and push changes
    #   run: |
    #     git config --global user.name 'GitHub Actions'
    #     git config --global user.email 'actions@users.noreply.github.com'
    #     git add pubspec.yaml
    #     git commit -m "Upgrade version to $NEW_VERSION"
    #     git push

    # - name: Increment version
    #     run: |
    #       flutter pub get
    #       flutter pub bump --major # Use --minor or --patch for minor or patch incrementations
    #       flutter pub get


  createRelease:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.2'
    - run: flutter clean
    - run: flutter pub get
    
    - name: Extract current version
      id: extract_version
      run: |
        VERSION=$(grep -oP 'version: \K[0-9.]+(\+\d+)?' pubspec.yaml)
        echo "::set-output name=version::$VERSION"

    - name: Build Android APK
      run: flutter build apk --release
    
    - name: Push APK to Releases
      uses: actions/upload-artifact@v2
      with:
        name: demo_v${{ steps.extract_version.outputs.version }}.apk
        path: |
          ${{ github.workspace }}/build/app/outputs/flutter-apk/app-release.apk
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
      with:
        tag_name: v${{ steps.extract_version.outputs.version }}
        release_name: Release ${{ steps.extract_version.outputs.version }}
        draft: false
        prerelease: false

    - name: Upload APKs
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/app/outputs/flutter-apk/app-release.apk
        asset_name: demo-release-${{ steps.increment_version.outputs.new_version }}.apk
        asset_content_type: application/vnd.android.package-archive
   